spring.application.name=order-service
spring.datasource.url=jdbc:postgresql://localhost:5432/order_service
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
resilience4j.circuitbreaker.instances.inventory.sliding-window-size=5

resilience4j.circuitbreaker.instances.inventory.failure-rate-threshold=50

resilience4j.circuitbreaker.instances.inventory.wait-duration-in-open-state=10s

resilience4j.circuitbreaker.instances.inventory.permitted-number-of-calls-in-half-open-state=3

resilience4j.circuitbreaker.instances.inventory.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.inventory.minimum-number-of-calls=5

management.endpoints.web.exposure.include=*
management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always

# Retry Configuration

resilience4j.retry.instances.inventoryRetry.max-attempts=3

resilience4j.retry.instances.inventoryRetry.wait-duration=2s

resilience4j.retry.instances.inventoryRetry.ignore-exceptions[0]=com.demo_project.order_service.exception.InventoryAccessDeniedException
resilience4j.retry.instances.inventoryRetry.ignore-exceptions[1]=com.demo_project.order_service.exception.InventoryUnauthorizedException

resilience4j.circuitbreaker.instances.inventory.ignore-exceptions[0]=com.demo_project.order_service.exception.InventoryAccessDeniedException
resilience4j.circuitbreaker.instances.inventory.ignore-exceptions[1]=com.demo_project.order_service.exception.InventoryUnauthorizedException

eureka.client.service-url.defaultZone=http://localhost:8761/eureka


spring.security.oauth2.client.registration.inventory.client-id=order-service
spring.security.oauth2.client.registration.inventory.client-secret=ltQLsz0qdQ61FiGopbjUlFDtIk4rNUTR

spring.security.oauth2.client.registration.inventory.authorization-grant-type=client_credentials

spring.security.oauth2.client.provider.inventory.token-uri=http://localhost:8181/realms/microservice-realm/protocol/openid-connect/token

logging.pattern.level=%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]

spring.cloud.openfeign.micrometer.enabled=true

logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.io.micrometer=DEBUG
